### PR TITLE
Added new images, and removed end of life images.

### PR DESCRIPTION
**Pull request by bemehiser**
- Added ubuntu-16.04 Dockerfile
- Updated README.md with new docker image
- Moved README.md to top level directory, instead of symlinking to subdirectory

### CODE REVIEW

**Review by zuazo — CHANGES_REQUESTED** [review]
Thanks @bemehiser!! :smiley: 

Can you move the README to the Debian subdirectory again? It is there for Docker Hub to read it and update correctly.

**Comment by bemehiser** [comment]
I believe DockerHub has fixed the issue where the README wouldn't be displayed unless it was in a subdirectory. I created a DockerHub project pulling from my fork, and the README displayed normally. https://hub.docker.com/r/bemehiser/chef-local/

**Review by zuazo — APPROVED** [review]
OK, thank you @bemehiser!

**Comment by zuazo** [comment]
I merged it, but new Fedora images are failing:

```
          Starting Chef Client, version 13.4.19
          [2017-10-19T18:42:38+00:00] WARN: Plugin Network: unable to detect ipaddress
          
          Running handlers:
          [2017-10-19T18:42:39+00:00] ERROR: Running exception handlers
          Running handlers complete
          [2017-10-19T18:42:39+00:00] ERROR: Exception handlers complete
          Chef Client failed. 0 resources updated in 00 seconds
          [2017-10-19T18:42:39+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
          [2017-10-19T18:42:39+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
          [2017-10-19T18:42:39+00:00] ERROR: Unable to determine node name: configure node_name or configure the system's hostname and fqdn
          [2017-10-19T18:42:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
  
  ERROR:  The command '/bin/sh -c chef-client -r "recipe[apt],recipe[netstat]"' returned a non-zero code: 1
  
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/docker_exception_parser.rb:156:in `raise_docker_error_exception'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/docker_exception_parser.rb:47:in `initialize'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:322:in `new'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:322:in `rescue in build_from_dir'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:319:in `build_from_dir'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:283:in `block in build_from_string'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:279:in `build_from_string'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:361:in `build_from_template'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/builder.rb:123:in `build'
# /home/travis/.rvm/gems/ruby-2.4.1/gems/dockerspec-0.2.0/lib/dockerspec/rspec_resources.rb:176:in `docker_build'
# ./spec/dockerfiles_spec.rb:36:in `block (3 levels) in <top (required)>'
# ./spec/dockerfiles_spec.rb:35:in `block (2 levels) in <top (required)>'
# ./spec/dockerfiles_spec.rb:34:in `block in <top (required)>'
# ./spec/dockerfiles_spec.rb:33:in `each'
# ./spec/dockerfiles_spec.rb:33:in `<top (required)>'
# ------------------
# --- Caused by: ---
# Docker::Error::UnexpectedResponseError:
#   /home/travis/.rvm/gems/ruby-2.4.1/gems/docker-api-1.33.6/lib/docker/util.rb:200:in `extract_id'
Finished in 0.00057 seconds (files took 4.63 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Any idea about how to fix the problem?

**Comment by bemehiser** [comment]
Apparently there were several issues with the `fedora` images.
- Fedora no longer includes `/bin/hostname`, which causes an error in testing
- Fedora seems to have systemd on all newer images, which made tests fail on `fedora:26`

[Updates](https://github.com/bemehiser/chef-local-docker/commit/35732299e56af9b2c19ddbc964ede7db2352978e) have been made, [tests pass](https://travis-ci.org/bemehiser/chef-local-docker/builds/290570400).

**Pull request merged**
