### PR TITLE
Fixed fedora images

### PR DESCRIPTION
**Pull request by bemehiser**
Apparently there were several issues with the `fedora` images.
- Fedora no longer includes `/bin/hostname`, which causes an error in testing
- Fedora seems to have systemd on all newer images, which made tests fail on `fedora:26`

### CODE REVIEW

**Review by zuazo — APPROVED** [review]
Wow! Thank you @bemehiser, for fixing it! :+1:

**Comment by bemehiser** [comment]
@zuazo Any chance you could also update the builds on https://hub.docker.com/ to build new images? Thanks!

**Comment by zuazo** [comment]
Docker Hub images should be updated automatically, aren't they?

**Comment by bemehiser** [comment]
The existing builds are updated (aka, if folder exists as a build job, say /debian-7, it will rebuild) but if a new folder (say /ubuntu-16.04) is added, dockerhub doesn't know about it, so won't build it unless you explicitly add it as a build job.

**Comment by zuazo** [comment]
Oh, yes! Of course. Sorry. Builds triggered. Let me know if anyone is missing.

**Pull request merged**
